### ISSUE TITLE
Bug Report: If you enable "Spam Prevention", when you press a note in-game, the game will crash.

### ISSUE THREAD

**Issue by SteveYT77** [Verwex/Funkin-Mic-d-Up-SC#89] opened 2021-07-09 15:41 UTC
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
Mic'd Up v2.0.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Go to options, gameplay, turn on spam prevention, open any song, press a note.

## Please describe your issue. Provide extensive detail and images if possible.
When you enable Spam Prevention in the options menu, under the gameplay tab, every time you press an incoming note, the game will crash. I tried by deleting and reinstalling the game entirely, only enabling that setting, and it crashed. None of the other settings cause this.

**Comment by cmd777** [comment] 2021-07-10 06:19
#70

**Comment by VMGuy23** [comment] 2021-07-10 10:07
Duplicate of #70

**Comment by haya3218** [comment] 2021-07-12 12:19
fixed as usual

**Closed by haya3218** 2021-07-12 12:19 UTC
Labels: bug, done for source code only
